addEvent ( "C:Teams", true )
addEventHandler ( "C:Teams", root, function ( nazwa, r, g, b )
	team = createTeam ( nazwa, r, g, b )
end)

addEvent ( "C:ChangeSkin", true )
addEventHandler ( "C:ChangeSkin", root, function ( skin, team, r, g, b, id, ilosc, x, y, z )
	spawnPlayer ( source, x, y, z, _, skin, 0, 0, getTeamFromName ( team ) )
	setPlayerNametagColor ( source, r, g, b )
	outputChatBox ( "Zostałeś zalogowany do teamu : "..team.." ze skinem : "..skin..". Miłej gry!", source, 255, 255, 255 )
	giveWeapon ( source, id, ilosc )
end)